alter table CARRIER_DELIVERY add constraint FK_CARRIER_DELIVERY_ON_CARRIER foreign key (CARRIER_ID) references CARRIER_CARRIER(ID);
alter table CARRIER_DELIVERY add constraint FK_CARRIER_DELIVERY_ON_TRUCK foreign key (TRUCK_ID) references CARRIER_TRUCK(ID);
create index IDX_CARRIER_DELIVERY_ON_CARRIER on CARRIER_DELIVERY (CARRIER_ID);
create index IDX_CARRIER_DELIVERY_ON_TRUCK on CARRIER_DELIVERY (TRUCK_ID);
